import fs from 'node:fs';
import path from 'node:path';

const CANDIDATES = ['public', 'dist', 'build', '_site', 'site', 'docs', 'out', 'www'];

/** Pick a publish dir: a common build-output dir containing index.html, else root. */
export function detectPublishDir(dir) {
  for (const c of CANDIDATES) {
    try {
      if (fs.statSync(path.join(dir, c)).isDirectory() && fs.existsSync(path.join(dir, c, 'index.html'))) {
        return c;
      }
    } catch { /* ignore */ }
  }
  return '.';
}

// Serve static files, deny dotfiles (.git/.env) and our own generated files.
const NGINX_CONF = `server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  location ~ /\\.(?!well-known) { deny all; }
  location ~ ^/(docker-compose\\.ya?ml|nginx-hormuz\\.conf)$ { deny all; }
  location / { try_files $uri $uri/ =404; }
}
`;

/**
 * Write a generated nginx compose that serves `publishDir` as a static site.
 * No Dockerfile needed from the user. Returns the compose filename.
 */
export function scaffoldStatic(dir, publishDir) {
  fs.writeFileSync(path.join(dir, 'nginx-hormuz.conf'), NGINX_CONF);
  const src = publishDir === '.' ? '.' : `./${publishDir}`;
  const compose = `# Generated by Hormuz Dock — static site (serves ${publishDir})
services:
  web:
    image: nginx:alpine
    ports:
      - "\${PORT:-8080}:80"
    volumes:
      - ${src}:/usr/share/nginx/html:ro
      - ./nginx-hormuz.conf:/etc/nginx/conf.d/default.conf:ro
`;
  fs.writeFileSync(path.join(dir, 'docker-compose.yml'), compose);
  return 'docker-compose.yml';
}
